# Generated by Django 4.1 on 2022-08-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('teacher_lastname', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('eeistu_url', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, verbose_name='Пара')),
                ('lesson_type', models.CharField(max_length=20, verbose_name='Тип пары')),
                ('lesson_auditory', models.CharField(max_length=15, verbose_name='Кабинет')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, verbose_name='День недели')),
                ('above_line', models.BooleanField()),
                ('lessons', models.ManyToManyField(related_name='day_lesson', to='schedule.lesson', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
    ]
