# Generated by Django 4.1 on 2022-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='above_line',
            field=models.BooleanField(verbose_name='Неделя над чертой'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(verbose_name='Время конца пары'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_teacher',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала пары'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='eeistu_url',
            field=models.SlugField(max_length=250, verbose_name='Ссылка на профиль'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ManyToManyField(related_name='lessons_teachers', to='schedule.teacher', verbose_name='Преподаватель'),
        ),
    ]
