# Generated by Django 4.1 on 2022-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_day_above_line_alter_lesson_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='eeistu_url',
            field=models.CharField(max_length=250, verbose_name='Ссылка на профиль'),
        ),
    ]
