# Generated by Django 4.1 on 2022-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_teacher_eeistu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_patronymic',
            field=models.CharField(max_length=70, null=True, verbose_name='Отчество'),
        ),
    ]
